import "./globals.css";
import "ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Whatsapp Clone",
  description: "Generated by cypherfelix",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.png" />
        <title>Whatsapp Clone</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
